config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'

  resources :admins, only: [:index, :update, :destroy]
  resource :admins do
    get 'manage_users' => 'admins#manage_users'
  end

  #get 'admins/manage_users' => 'admins#manage_users'

  resource :homes, only: [:index, :new, :create] do
    resources :images, only: [:index, :show, :update, :destroy]
    resources :albums, only: [:show, :update, :destroy ]
    member do
      get 'new' , as: 'upload'
      post 'image_upload'            => 'homes#image_create'
      get 'show/:id'                => 'homes#show', as: 'show_image'
      post 'like_image/:id'         => 'homes#like_image', as: 'like_image'
      get 'show_publish_album/:id'  => 'homes#show_publish_album', as: 'show_publish_album'
      post 'like_album/:id'         => 'homes#like_album', as: 'like_album'
      post 'follow_album/:id'       => 'homes#follow_album', as: 'follow_album'
      post 'follow_user/:id'        => 'homes#follow_user', as: 'follow_user'
      post 'clear_notifications/:id'=> 'homes#clear_notifications', as: 'clear_notifications'
      get 'show_publish_user/:id'   => 'homes#show_publish_user', as: 'show_publish_user'

    end
  end
  #post 'homes/image_upload' => 'homes#image_create'

  #get 'homes/show/:id' => 'homes#show', as: 'show_image'
  #post 'homes/like_image/:id' => 'homes#like_image', as: 'like_image'

  #get 'homes/show_publish_album/:id' => 'homes#show_publish_album', as: 'show_publish_album'
  #post 'homes/like_album/:id' => 'homes#like_album', as: 'like_album'
  #post 'homes/follow_album/:id' => 'homes#follow_album', as: 'follow_album'
  #post 'homes/follow_user/:id' => 'homes#follow_user', as: 'follow_user'
  #post 'homes/clear_notifications/:id' => 'homes#clear_notifications', as: 'clear_notifications'

  #get 'homes/show_publish_user/:id' => 'homes#show_publish_user', as: 'show_publish_user'

  #get 'homes/new' , as: 'upload'


  devise_for :users, controllers: { registrations: 'users/registrations' }

end

app/views/pages/_album_form.html.erb
<div class="col-xs-12 col-sm-4 col-md-4 ">
  <div class="albumdetail">
    <div class="modal-body" style="padding:40px 50px;">
      <%= form_for :album, url: homes_album_path(album), method: :patch   do |form| %>

        <div class="field">
          <%= form.label :title %><br />
          <%= form.text_field :title, class: "form-control", value: album.title%>
        </div>

        <div class="field">
          <%= form.label :description %><br />
          <%= form.text_field :description, class: "form-control",  value: album.description%>
        </div>

        <p>
          <%if album.publish %>
            <%= form.label :publish, 'Private' %>
            <%= radio_button(:album, "publish", false)%>
            <%= form.label :publish, 'Publish' %>
            <%= radio_button(:album, "publish", true, checked: true)%>
          <%else%>
            <%= form.label :publish, 'Private' %>
            <%= radio_button(:album, "publish", false, checked: true)%>
            <%= form.label :publish, 'Publish' %>
            <%= radio_button(:album, "publish", true)%>
          <%end%>

        </p>

        <div class="actions">
          <%= form.submit "Update", class:"btn btn-success btn-block"%>
        </div>
      <% end %>
      <%= form_for :album, url: homes_album_path(album), method: :delete do |form| %>
        <div class="actions">
          <%= form.submit "Delete", class:"btn btn-danger btn-block"%>
        </div>
        <% end %>

      <% flash.each do |key, value|%>
      <div class="alert alert-warning alert-dismissable fade in myNotice">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
          <p><%= key %> : <%= value %></p>
      </div>
      <%end%>
    </div>
  </div>
</div>

app/views/pages/_footer.html.erb
<footer>
  <div class="container">
  </div>
</footer>

app/views/pages/_header.html.erb
<header class="headsection">
  <div class="container">
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="nav-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapse-navs" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>

        <div class="collapse navbar-collapse" id="collapse-navs">
          <ul class="nav navbar-nav navbar-left">
            <li><%= link_to 'Home', root_path %></li>
            <%if user_signed_in?%>

                <%if current_user.admin?%>
                  <!-- Admin menu-->
                  <li class="nav-divider"></li>
                  <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Admin
                      <span class="caret"></span>
                    </a>
                      <ul class="dropdown-menu">
                        <li><%= link_to 'Manage Images', admins_path%></li>
                        <li><%= link_to 'Manage Users',manage_users_admins_path%></li>
                      </ul>
                  </li>
                <%end%>
                  <li class="nav-divider"></li>
                  <li><%= link_to 'Images', homes_images_path%></li>
                  <!-- Notification-->
                  <li class="nav-divider"></li>
                  <li class="dropdown">
                    <%= link_to '', href: clear_notifications_homes_path(current_user), class: 'dropdown-toggle',
                        data:{toggle: 'dropdown'}, method: :post, remote: true do%>
                      <span class="badge notification" id="notificationNumber"><%=notifications ? notifications.unread.size : 0 %></span><i class="fa fa-flag" aria-hidden="true"></i>
                    <%end%>
                      <%unless notifications.empty?%>
                        <ul class="dropdown-menu" id="notificationItems">
                          <%notifications.each do |notification|%>
                            <%= link_to '', href: notification.link do%>
                              <%if notification.readed%>
                                  <li class="readedNotification"><%=notification.content%></li>
                              <%else%>
                                  <li><%=notification.content%></li>
                              <%end%>
                            <%end%>
                          <%end%>
                        </ul>
                      <%end%>
                  </li>
              <li class="nav-divider"></li>
              <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %> </li>
            <%else%>
              <li class="nav-divider"></li>
              <li><%= link_to 'Log In', new_user_session_path %> </li>
            <%end%>
          </ul>
        </div>
      </div>
    </nav>
  </div>
</header>

app/views/pages/_image_of_album.html.erb
<div class="col-xs-12 col-sm-8 col-md-8 ">
  <div id="showImages" class="tab-pane fade in active">

      <div class="row" >
        <% images.each do |img|%>
          <div class="col-xs-6 col-sm-4 col-md-3 imagesitem">
            <a href=<%= homes_image_path(img)%>>
              <%= image_tag(img.img_content.url(:thumb), alt: "image missing", class:"img-thumbnail")%>
            </a>
          </div>
        <%end%>

        <!-- Upload button -->
        <div class="col-xs-6 col-sm-4 col-md-3 imagesitem text-center">
            <button type="button" id="addImageToAlbum" class="btn btn-default"
            data-toggle="tooltip" title="Add Image" data-placement="right">
              <i class="glyphicon glyphicon-plus fa-4x" aria-hidden="true"></i>
            </button>
        </div>
      </div>
      <!-- Upload image model -->
      <div class="modal fade" id="uploadModal" role="dialog">
        <div class="modal-dialog">
          <!-- Modal content-->
          <div class="modal-content">
            <div class="modal-header" style="padding:35px 50px;">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h4>Upload more images</h4>
            </div>
            <div class="modal-body" style="padding:40px 50px;">
              <%= form_for :album, class: "form-group", url: homes_album_path(album),
              html: { multipart: true }, method: :patch do |form| %>
              <div class="field">
                <%= form.label :title %><br />
                <%= form.text_field :title, class: "form-control", value: album.title%>
              </div>

              <div class="field">
                <%= form.label :description %><br />
                <%= form.text_field :description, class: "form-control",  value: album.description%>
              </div>

              <p>
                <%if album.publish %>
                  <%= form.label :publish, 'Private' %>
                  <%= radio_button(:album, "publish", false)%>
                  <%= form.label :publish, 'Publish' %>
                  <%= radio_button(:album, "publish", true, checked: true)%>
                <%else%>
                  <%= form.label :publish, 'Private' %>
                  <%= radio_button(:album, "publish", false, checked: true)%>
                  <%= form.label :publish, 'Publish' %>
                  <%= radio_button(:album, "publish", true)%>
                <%end%>

              </p>

              <p>
              <%= form.label :description, 'Picked images' %>
              <%= form.file_field :img_contents, multiple: true %>
              </p>
              <%= form.submit 'Upload', class: "btn btn-success"%>
              <% end %>
            </div>
            <div class="modal-footer">
              <button type="submit" class="btn btn-danger btn-default pull-left" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> Cancel</button>
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
          <%= paginate images, window: Image::PAGINATING_WINDOW, :param_name => "album_img_page" %>
        </div>
      </div>
  </div>
</div>

app/views/pages/_publish.html.erb
<section class="featuresection">
  <div class="container">
    <div class="title">
    </div>
    <div class="listImage">
      <div class="row" >
        <% if publish_images%>
          <% publish_images.each do |img|%>
            <div class="col-xs-6 col-sm-4 col-md-3 publishImage">
              <a href="<%=show_image_homes_path(img)%>">
               <%= image_tag(img.img_content.url(:thumb), alt: "image missing", class:"img-thumbnail")%>
             </a>
            </div>
          <%end%>
        <%end%>
      </div>
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
          <%= paginate publish_images, window: Image::PAGINATING_WINDOW, :param_name => "page" %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/pages/_service.html.erb
<section class="servicesection">
  <div class="container">
    <div class="row">
      <div class="col-md-6" >
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
         <!-- Indicators -->
         <ol class="carousel-indicators">
           <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
           <li data-target="#myCarousel" data-slide-to="1"></li>
           <li data-target="#myCarousel" data-slide-to="2"></li>
           <li data-target="#myCarousel" data-slide-to="3"></li>
         </ol>

         <!-- Wrapper for slides -->
         <div class="carousel-inner" role="listbox">
           <div class="item active">
             <%= image_tag("img01.jpg", size: "460x345", alt: "image01 missing")%>
           </div>

           <div class="item">
             <%= image_tag("img02.jpg", size: "460x345", alt: "image02 missing")%>
           </div>

           <div class="item">
             <%= image_tag("img03.jpg", size: "460x345", alt: "image03 missing")%>
           </div>

           <div class="item">
             <%= image_tag("img04.png", size: "460x345", alt: "image04 missing")%>
           </div>
         </div>

         <!-- Left and right controls -->
         <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
           <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
           <span class="sr-only">Previous</span>
         </a>
         <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
           <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
           <span class="sr-only">Next</span>
         </a>
       </div>
      </div>

      <div class="col-md-6 text-center">
        <a href= <%=upload_homes_path%> data-toggle="tooltip" title="Upload Images" data-placement="right">
          <button type="button" class="btn btn-default" id="uploadBtn">
            <i class="fa fa-upload fa-5x" aria-hidden="true"></i>
          </button>
        </a>
      </div>
    </div>
  </div>
</section>

app/views/pages/_show_album_detail.html.erb
<section class="showimagesection">
  <div class="container">
    <div class="row">
      <%= render partial:'pages/image_of_album', locals: {images: images, album: album}%>
      <%= render partial:'pages/album_form', locals: {album: album}%>
    </div>
  </div>
</section>

app/views/pages/_show_image_admin.html.erb
<section class="imagealbumsection">
  <div class="container">
    <div class="row">
      <% images.each do |img|%>
        <div class="col-xs-12 col-sm-6 col-md-6 ">
          <div class="row imageItem">
            <div class="col-xs-12 col-sm-6 col-md-6">
              <%= image_tag(img.img_content.url(:thumb), alt: "image missing", class:"img-thumbnail")%>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-6 ">
              <div class="imageAction">
                <p><strong>Title:<%= img.title%></strong></p>
                <p><strong>Description:</strong></p>
                <p><%= img.description%></p>
                <p><strong>Owner: <%=img.album.user.name%></strong></p>

                <a data-confirm="Are you sure?" data-method="delete" href=<%=homes_image_path(img)%>>
                  <button type="button" class="btn btn-danger">Delete</button>
                </a>
                <a href=<%=homes_image_path(img)%>>
                  <button type="button" class="btn btn-success">Update</button>
                </a>
              </div>
            </div>
          </div>
        </div>
      <%end%>
    </div>

    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12">
          <%= paginate images, window: Image::PAGINATING_WINDOW, :param_name => "imagepage" %>
      </div>
    </div>
  </div>
</section>

app/views/pages/_show_image_album.html.erb
<section class="imagealbumsection">
  <div class="container">
    <ul class="nav nav-tabs">
      <li class="active"><a data-toggle="tab" href="#showImages">Images</a></li>
      <li><a data-toggle="tab" href="#showAlbums">Albums</a></li>
    </ul>

    <div class="tab-content">
      <div id="showImages" class="tab-pane fade in active">
        <div class="row" >
          <% images.each do |img|%>
            <div class="col-xs-6 col-sm-4 col-md-3 imagesitem">
              <a href=<%= homes_image_path(img)%>>
                <%= image_tag(img.img_content.url(:thumb), alt: "image missing", class:"img-thumbnail")%>
              </a>
            </div>
          <%end%>
        </div>
        <div class="row">
          <div class="col-xs-12 col-sm-12 col-md-12">
            <%= paginate images, window: Image::PAGINATING_WINDOW, :param_name => "imagepage" %>
          </div>
        </div>
      </div>
      <div id="showAlbums" class="tab-pane fade ">
          <div class="row">
            <% albums.each do |album|%>
              <div class="col-xs-12 col-sm-6 col-md-4 albumsitem">
                <div class="albums">
                  <a target="_blank" href=<%=homes_album_path(album)%>>
                    <%if album.images.first%>
                      <%= image_tag(album.images.first.img_content.url(:thumb), alt: "image missing")%>
                    <%else%>
                      <%= image_tag('404.png', alt: "image missing")%>
                    <%end%>
                  </a>
                  <div class="title"><%= album.title %> </div>
                    <div class="description"><%= album.description %></div>
                  </div>
              </div>
            <%end%>
          </div>
          <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
              <%= paginate albums, window: Image::PAGINATING_WINDOW, :param_name => "albumpage" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/pages/_show_image_detail.html.erb
<section class="showimagesection">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-12">
        <div class="showimage text-center">
          <%= image_tag(image.img_content.url(:original), alt: "image missing")%>
        </div>
      </div>
      <div class="col-sm-12 col-md-12">
        <div class="imageinfo">
          <div class="modal-body" style="padding:40px 50px;">
            <%= form_for :updated_image, url: homes_image_path(image), method: :patch   do |f| %>
              <div class="field">
                <label> Album: <%=image.album.title %> </label>
              </div>

              <div class="field">
                <%= f.label :title %><br />
                <%= f.text_field :title, class: "form-control", value: image.title%>
              </div>

              <div class="field">
                <%= f.label :description %><br />
                <%= f.text_field :description, class: "form-control",  value: image.description%>
              </div>

              <div class="field">
                <%if publish %>
                  <%= f.label :publish, 'Private' %>
                  <%= radio_button(:updated_image, "publish", false)%>
                  <%= f.label :publish, 'Publish' %>
                  <%= radio_button(:updated_image, "publish", true, checked: true)%>
                <%else%>
                  <%= f.label :publish, 'Private' %>
                  <%= radio_button(:updated_image, "publish", false, checked: true)%>
                  <%= f.label :publish, 'Publish' %>
                  <%= radio_button(:updated_image, "publish", true)%>
                <%end%>
              </div>

              <div class="actions">
                <%= f.submit "Update", class:"btn btn-success btn-block"%>
              </div>
            <% end %>
            <%= form_for :updated_image, url: homes_image_path(image), method: :delete   do |f| %>
              <div class="actions">
                <%= f.submit "Delete", class:"btn btn-danger btn-block"%>
              </div>
            <% end %>
            <% flash.each do |key, value|%>
            <div class="alert alert-warning alert-dismissable fade in myNotice">
              <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <p><%= key %> : <%= value %></p>
            </div>
            <%end%>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/pages/_show_user_admin.html.erb
  <section class="imagealbumsection">
  <div class="container">
    <div class="row">
      <% users.each do |user|%>
        <div class="col-xs-12 col-sm-6 col-md-6 ">
          <div class="row imageItem">
            <div class="col-xs-12 col-sm-6 col-md-6">
              <%= image_tag('avatar.png', alt: "image missing", class:"img-thumbnail")%>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-6 ">
              <div class="imageAction">
                <p><strong>Name:<%= user.name%></strong></p>
                <p><strong>Email: <%= user.email%></strong></p>
                <p><strong>Status: <%= user.active ? 'Active' : 'Disable' %> </strong></p>
                <p>
                  <a data-confirm="Are you sure?" data-method="delete" href=<%=admin_path(user)%>>
                    <button type="button" class="btn btn-danger">Delete</button>
                  </a>
                  <%if user.active%>
                    <%=link_to '', href: admin_path(user), method: :patch do %>
                      <button type="button" class="btn btn-warning">Disable</button>
                    <%end%>
                  <%else%>
                    <%=link_to '', href: admin_path(user), method: :patch do %>
                      <button type="button" class="btn btn-success">Active</button>
                    <%end%>
                  <%end%>
                </p>
              </div>
            </div>
          </div>
        </div>
      <%end%>
    </div>

    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12">
        <%= paginate users, window: Image::PAGINATING_WINDOW, :param_name => "userpage" %>
      </div>
    </div>
  </div>
</section>

app/views/pages/_upload.html.erb
<div class="container">
  <ul class="nav nav-tabs">
    <li id="albumTab" class="active"><a data-toggle="tab" href="#albumUpload">Album Upload</a></li>
    <li id="imageTab"><a data-toggle="tab" href="#imageUpload">Image Upload</a></li>
  </ul>

  <div class="tab-content">
    <div id="albumUpload" class="tab-pane fade in active">
      <%= form_for :album, class: "form-group", url: homes_path, html: { multipart: true } do |form| %>
        <p>
          <%= form.label :title%>
          <%= form.text_field :title, class: "form-control" %>
        </p>

        <p>
          <%= form.label :description %>
          <%= form.text_field :description, class: "form-control"  %>
        </p>

        <p>
          <%= form.label :publish, 'Private' %>
          <%= radio_button(:album, "publish", false, checked: true)%>
          <%= form.label :publish, 'Publish' %>
          <%= radio_button(:album, "publish", true)%>
        </p>

        <p>
          <%= form.label :description, 'Picked images' %>
          <%= form.file_field :img_contents, multiple: true %>
        </p>
          <%= form.submit 'Upload', class: "btn btn-success"%>
      <% end %>
    </div>
    <div id="imageUpload" class="tab-pane fade">
      <%= form_for :image, class: "form-group", url: image_upload_homes_path, html: { multipart: true } do |form| %>
        <p>
          <%= form.label :album%>
          <%=  collection_select(:image, :album_id, @albums, :id, :title, { prompt: true }) %>
        </p>

        <p>
          <%= form.label :title%>
          <%= form.text_field :title, class: "form-control" %>
        </p>

        <p>
          <%= form.label :description %>
          <%= form.text_field :description, class: "form-control"  %>
        </p>

        <p>
          <%= form.label :publish, 'Private' %>
          <%= radio_button(:image, "publish", false, checked: true)%>
          <%= form.label :publish, 'Publish' %>
          <%= radio_button(:image, "publish", true)%>
        </p>

        <p>
          <%= form.file_field :img_content %>
        </p>
          <%= form.submit 'Upload', class: "btn btn-success"%>
      <% end %>
    </div>
  </div>
  <% flash.each do |key, value|%>
  <div class="alert alert-warning alert-dismissable fade in myNotice">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
      <p><%= key %> : <%= value %></p>
  </div>
  <%end%>
</div>