config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'

  resources :admins, only: [:index, :update, :destroy]
  resource :admins do
    get 'manage_users' => 'admins#manage_users'
  end

  #get 'admins/manage_users' => 'admins#manage_users'

  resource :homes, only: [:index, :new, :create] do
    resources :images, only: [:index, :show, :update, :destroy]
    resources :albums, only: [:show, :update, :destroy ]
    member do
      get 'new' , as: 'upload'
      post 'image_upload'            => 'homes#image_create'
      get 'show/:id'                => 'homes#show', as: 'show_image'
      post 'like_image/:id'         => 'homes#like_image', as: 'like_image'
      get 'show_publish_album/:id'  => 'homes#show_publish_album', as: 'show_publish_album'
      post 'like_album/:id'         => 'homes#like_album', as: 'like_album'
      post 'follow_album/:id'       => 'homes#follow_album', as: 'follow_album'
      post 'follow_user/:id'        => 'homes#follow_user', as: 'follow_user'
      post 'clear_notifications/:id'=> 'homes#clear_notifications', as: 'clear_notifications'
      get 'show_publish_user/:id'   => 'homes#show_publish_user', as: 'show_publish_user'

    end
  end
  #post 'homes/image_upload' => 'homes#image_create'

  #get 'homes/show/:id' => 'homes#show', as: 'show_image'
  #post 'homes/like_image/:id' => 'homes#like_image', as: 'like_image'

  #get 'homes/show_publish_album/:id' => 'homes#show_publish_album', as: 'show_publish_album'
  #post 'homes/like_album/:id' => 'homes#like_album', as: 'like_album'
  #post 'homes/follow_album/:id' => 'homes#follow_album', as: 'follow_album'
  #post 'homes/follow_user/:id' => 'homes#follow_user', as: 'follow_user'
  #post 'homes/clear_notifications/:id' => 'homes#clear_notifications', as: 'clear_notifications'

  #get 'homes/show_publish_user/:id' => 'homes#show_publish_user', as: 'show_publish_user'

  #get 'homes/new' , as: 'upload'


  devise_for :users, controllers: { registrations: 'users/registrations' }

end

app/views/publishs/_list_image_album.html.erb
<div id="showImages" class="tab-pane fade in active">
  <div class="row" >
    <% images.each do |img|%>
      <div class="col-xs-6 col-sm-4 col-md-3 imagesitem">
        <a href= "<%= show_image_homes_path(img)%>" >
          <%= image_tag(img.img_content.url(:thumb), alt: "image missing", class:"img-thumbnail")%>
        </a>
      </div>
    <%end%>
  </div>

  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
      <%= paginate images, window: Image::PAGINATING_WINDOW, :param_name => "album_img_page" %>
    </div>
  </div>
</div>

app/views/publishs/_publish_album_detail.html.erb
<section class="publishAlbumSection">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-8 col-md-8 ">
        <%= render partial: 'publishs/list_image_album', locals:{images: images}%>
      </div>

      <div class="col-xs-12 col-sm-4 col-md-4 albumdetail">
        <p><strong>Album: <a href="#"><%= album.title %></a></strong></p>
        <p><%= album.description %></p>
        <p><strong>Owner: <a href="<%=show_publish_user_homes_path(owner)%>"><%=owner.name%></a></strong></p>
        <p>
          <a href="#"><span id="likeBadge" class="badge"><%=album.likes.size%></span>Like</a>
        </p>
        <%if user_signed_in?%>
          <%= link_to like_album_homes_path(album, like: true), method: 'post', remote: true do %>
            <button type="button" class="btn btn-primary" id="likeButton"><%= liked ? 'Unlike': 'Like'%></button>
          <%end%>
        <%end%>
      </div>
    </div>
  </div>
</section>

app/views/publishs/_published_image.html.erb
<div class="publishImage">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-8">
        <div class="showimage text-center">
          <%= image_tag(image.img_content.url(:original), alt: "image missing")%>
        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-4 imageInfo">
        <p><strong>Title: <%= image.title %></strong></p>
        <p><strong>Album: <a href="<%=show_publish_album_homes_path(album)%>"><%= album.title %></a></strong></p>
        <p><strong>Owner: <a href="<%=show_publish_user_homes_path(owner)%>"><%=owner.name%></a></strong></p>
        <p>
          <a href="#"><span id="likeBadge" class="badge"><%=image.likes.size%></span>Like</a>
        </p>
        <%if user_signed_in?%>
          <%= link_to like_image_homes_path(image, like: true), method: 'post', remote: true do %>
            <button type="button" class="btn btn-primary" id="likeButton"><%= liked ? 'Unlike' : 'Like'%></button>
          <%end%>
        <%end%>
      </div>
    </div>
  </div>
</div>

app/views/publishs/_show_publish_profile.html.erb
<section class="publishProfileSection">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-md-8">
        <%= render partial: 'publishs/list_image_album', locals:{images: images}%>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-4 profile">
        <div class="row">
          <div class="col-xs-12 col-sm-12 col-md-12 text-center profileImage">
              <%= image_tag('avatar.png', alt: "image missing", class:"img-thumbnail")%>
          </div>
          <div class="col-xs-12 col-sm-12 col-md-12 profileInfo">
            <p><strong>Name: <a href="<%=show_publish_user_homes_path(user)%>"><%=user.name%></a></strong></p>
            <p><strong>Email: <a href="<%=show_publish_user_homes_path(user)%>"><%=user.email%></a></strong></p>
            <p>
              <a href="#"><span class="badge" id="followBadge"><%=user.follows.size%></span>Follower</a>
            </p>
            <%if user_signed_in? && current_user.id != user.id%>
              <%= link_to follow_user_homes_path(user, follow: true), method: 'post', remote: true do %>
                <button type="button" class="btn btn-primary" id="followButton"><%= followed ? 'Unfollow' : 'Follow'%></button>
              <%end%>
            <%end%>
          </div>
      </div>
      </div>
    </div>
  </div>
</section>